### ISSUE TITLE
[Data] Bathymatry and Federal and State Waters layers legend override

### ISSUE THREAD

**Issue by tyqi11** [macmods/sfi#49]
![WeChat Screenshot_20201123164734](https://user-images.githubusercontent.com/22883947/100031924-aa9cea80-2dab-11eb-85aa-c6a6533c8ba0.png)
![WeChat Screenshot_20201123164751](https://user-images.githubusercontent.com/22883947/100031928-ac66ae00-2dab-11eb-932a-119f50536151.png)

Using data layers hosted by NOAA is still the best idea since no more manual work is required when the data source is updated. So, we'd better think of a way to override the legend rendering.

**Comment by soobinchoi54** [comment]
Bathymetry layer legend override has been resolved in PR #84 and State and Federal Waters is no longer an issue after replacing NOAA's URL with Christina's
