### ISSUE TITLE
[Widgets] Print widget UI logic issue 

### ISSUE THREAD

**Issue by soobinchoi54** [macmods/sfi#81]
**How to reproduce:** 
Click on print button on summary report, then click on it again -- we get two widgets instead of making the existing one invisible.
**Expected outcome:**

1. We need an "x" button on the widget itself so that users can close it. 
2. By clicking on the print button when it's open, the widget should close.

<img width="1536" alt="Screen Shot 2020-12-04 at 3 58 29 PM" src="https://user-images.githubusercontent.com/41706004/101226515-8eba0400-3649-11eb-9b9f-2972d1702e0f.png">

**Comment by oscarli9** [comment]
Now the print widget will be open only after the print button is clicked. By clicking any other button, it will be closed.

**Comment by soobinchoi54** [comment]
Looks great, thanks for resolving this!
